### ISSUE TITLE
Add promotional pics

### ISSUE THREAD

**Issue by RosaWagner** [Omnibus-Type/Ballet#4]
Same as for Sansita Swashed, and it can apply to all the fonts in the process of being released on GF ;)
Can you add a "documentation" folder containing 2-3 pics, why not a video, so we can tweet about it ?

Or you can send it to me by email if you want to keep the images secret for a more surprising announcement haha

Thanks a lot!

**Comment by Omnibus-Type** [comment]
We write to you by mail :)
